# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 13:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0004_auto_20171103_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='players',
        ),
        migrations.AddField(
            model_name='record',
            name='players',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
