# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20171103_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='players',
            new_name='player',
        ),
    ]
