# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 13:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20171103_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='player',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
